// ─── Projects data ───────────────────────────────────────────
export const PROJECTS = [
  {
    id: 1,
    title: 'Cyberspace Portfolio',
    category: 'Frontend / 3D',
    description: 'A stunning Three.js portfolio with particle starfields, glassmorphic cards, and a scroll-driven car animation on a neon road.',
    tech: ['React', 'Three.js', 'GSAP', 'TailwindCSS', 'Framer Motion'],
    accentColor: '#00f0ff',
    accentColor2: '#b026ff',
    github: '#',
    live: '#',
    featured: true,
  },
  {
    id: 2,
    title: 'MotoParts E-Commerce',
    category: 'Full-Stack',
    description: 'A full-stack e-commerce platform for motorcycle parts with advanced search, filtering, real-time inventory, and Stripe payments.',
    tech: ['Next.js', 'MongoDB', 'Stripe', 'Tailwind', 'Node.js'],
    accentColor: '#ff003c',
    accentColor2: '#ffd700',
    github: '#',
    live: '#',
    featured: true,
  },
  {
    id: 3,
    title: 'NexaFlow Dashboard',
    category: 'SaaS / Dashboard',
    description: 'A real-time SaaS analytics dashboard with drag-and-drop widgets, live data charts, role-based access control and dark mode.',
    tech: ['React', 'Chart.js', 'Firebase', 'TailwindCSS'],
    accentColor: '#b026ff',
    accentColor2: '#00f0ff',
    github: '#',
    live: '#',
    featured: true,
  },
  {
    id: 4,
    title: 'Zenith Landing Page',
    category: 'Frontend / Marketing',
    description: 'A high-converting SaaS landing page with scroll animations, 3D hero section, social proof tiles, and A/B-tested CTAs.',
    tech: ['HTML', 'GSAP', 'Three.js', 'Vanilla CSS'],
    accentColor: '#ffd700',
    accentColor2: '#ff003c',
    github: '#',
    live: '#',
    featured: false,
  },
  {
    id: 5,
    title: 'Aman Enterprises Website',
    category: 'Business / Corporate',
    description: 'Corporate website for a manpower supply company showcasing services for Polyplex and Patanjali with multilingual support.',
    tech: ['Next.js', 'TailwindCSS', 'Framer Motion'],
    accentColor: '#00f0ff',
    accentColor2: '#ffd700',
    github: '#',
    live: '#',
    featured: false,
  },
  {
    id: 6,
    title: 'Document Portal',
    category: 'Full-Stack / Admin',
    description: 'Full-stack document management system with upload, preview, search, role-based access and admin dashboard built on Next.js.',
    tech: ['Next.js', 'PostgreSQL', 'S3', 'NextAuth'],
    accentColor: '#b026ff',
    accentColor2: '#ff003c',
    github: '#',
    live: '#',
    featured: false,
  },
]

// ─── Services data ────────────────────────────────────────────
export const SERVICES = [
  {
    icon: '🌐',
    title: 'Landing Pages',
    description: 'High-converting, visually stunning landing pages that captivate visitors and drive action. Optimised for speed and SEO.',
    features: ['Custom 3D animations', 'SEO & Performance optimized', 'Responsive design', 'CMS integration'],
  },
  {
    icon: '🛒',
    title: 'E-Commerce Stores',
    description: 'Full-featured online stores with payment gateways, inventory management, and seamless checkout experiences.',
    features: ['Stripe / Razorpay', 'Product management', 'Order tracking', 'Admin dashboard'],
  },
  {
    icon: '⚡',
    title: 'Web Applications',
    description: 'Scalable, full-stack React & Next.js web apps with real-time features, APIs, and database integrations.',
    features: ['REST & GraphQL APIs', 'Authentication', 'Real-time features', 'Cloud deployment'],
  },
  {
    icon: '🎮',
    title: '3D / Interactive Sites',
    description: 'Immersive Three.js + WebGL experiences with scroll-driven animations, 3D models, and interactive scenes.',
    features: ['Three.js / WebGL', 'GSAP scroll animations', 'Interactive 3D models', 'Shader effects'],
  },
]

// ─── Pricing plans ────────────────────────────────────────────
export const PRICING = [
  {
    name: 'Starter',
    makingCost: '$199',
    hostingCost: '$5 – $10',
    hostingNote: '/month (Vercel + Domain)',
    description: 'Perfect for small businesses, freelancers, or personal brands needing a polished web presence.',
    features: [
      '3–5 page static website',
      'Responsive design',
      'Basic SEO setup',
      'Contact form',
      'Delivery in 5–7 days',
    ],
    highlight: false,
  },
  {
    name: 'Pro',
    makingCost: '$499',
    hostingCost: '$15 – $30',
    hostingNote: '/month (VPS + SSL)',
    description: 'Full-stack web app or e-commerce store with CMS, payments, and admin panel.',
    features: [
      'Full-stack Next.js app',
      'Payment integration',
      'Admin dashboard',
      'Database + API',
      '3D / interactive elements',
      'Delivery in 14–21 days',
    ],
    highlight: true,
  },
  {
    name: 'Enterprise',
    makingCost: 'Custom',
    hostingCost: 'Custom',
    hostingNote: 'on infrastructure requirements',
    description: 'Complex systems with microservices, cloud infrastructure, real-time features, and dedicated support.',
    features: [
      'Microservices architecture',
      'Custom cloud setup (AWS/GCP)',
      'CI/CD pipeline',
      'Dedicated maintenance',
      'SLA-backed support',
      'Timeline: discussion based',
    ],
    highlight: false,
  },
]
