// ─── Projects data ───────────────────────────────────────────
export const PROJECTS = [
  {
    id: 1,
    title: 'Cyberspace Portfolio',
    category: 'Frontend / 3D',
    description: 'A stunning Three.js portfolio with particle starfields, glassmorphic cards, and a scroll-driven car animation on a neon road.',
    descriptionHin: 'Ek makkhan Three.js portfolio jisme car aur stars dono hain. Pura neon vibe aur scroll animation ke sath.',
    tech: ['React', 'Three.js', 'GSAP', 'TailwindCSS', 'Framer Motion'],
    accentColor: '#00f0ff',
    accentColor2: '#b026ff',
    github: 'https://github.com/AmanJaiSingh/Aman.dev',
    live: '#',
    image: '/projects/01_Cyberspace_Portfolio.png',
    featured: true,
  },
  {
    id: 2,
    title: 'MotoParts E-Commerce',
    category: 'Full-Stack',
    description: 'A full-stack e-commerce platform for motorcycle parts with advanced search, filtering, real-time inventory, and Stripe payments.',
    descriptionHin: 'Motorcycle parts ka pura full-stack dukan. Live stock tracking aur payment gateway bhi chal ra hai ekdum properly.',
    tech: ['Next.js', 'MongoDB', 'Stripe', 'Tailwind', 'Node.js'],
    accentColor: '#ff003c',
    accentColor2: '#ffd700',
    github: 'https://github.com/AmanJaiSingh/Moto_parts',
    live: '#',
    image: '',
    featured: true,
  },
  {
    id: 3,
    title: 'NexaFlow Dashboard',
    category: 'SaaS / Dashboard',
    description: 'A real-time SaaS analytics dashboard with drag-and-drop widgets, live data charts, role-based access control and dark mode.',
    descriptionHin: 'SaaS admin panel jisme drag-drop widgets, live charts aur roles hain. Dark mode toh by default solid hi hota hai.',
    tech: ['React', 'Chart.js', 'Firebase', 'TailwindCSS'],
    accentColor: '#b026ff',
    accentColor2: '#00f0ff',
    github: 'https://github.com/AmanJaiSingh/NexaFlow',
    live: 'https://nexa-flow-zeta.vercel.app/',
    image: '/projects/02_NexaFlow_Normal_SS.png',
    featured: true,
  },
  {
    id: 4,
    title: 'Zenith Landing Page',
    category: 'Frontend / Marketing',
    description: 'A high-converting SaaS landing page with scroll animations, 3D hero section, social proof tiles, and A/B-tested CTAs.',
    descriptionHin: 'Landing page aisi jo conversion laaye. Scroll par zabardast animations aur 3D hero section ka jalwa.',
    tech: ['HTML', 'GSAP', 'Three.js', 'Vanilla CSS'],
    accentColor: '#ffd700',
    accentColor2: '#ff003c',
    github: 'https://github.com/AmanJaiSingh/Zenith',
    live: 'https://zenith-delta-nine.vercel.app/',
    image: '/projects/03_Zenith_Normal_SS.png',
    featured: false,
  },
  {
    id: 5,
    title: 'Aman Enterprises Website',
    category: 'Business / Corporate',
    description: 'Corporate website for a manpower supply company showcasing services for Polyplex and Patanjali with multilingual support.',
    descriptionHin: 'Manpower supply walon ka professional site jisme Polyplex aur Patanjali jaise clients ke details hain.',
    tech: ['Next.js', 'TailwindCSS', 'Framer Motion'],
    accentColor: '#00f0ff',
    accentColor2: '#ffd700',
    github: '#',
    live: '#',
    image: '',
    featured: false,
  },
  {
    id: 6,
    title: 'Document Portal',
    category: 'Full-Stack / Admin',
    description: 'Full-stack document management system with upload, preview, search, role-based access and admin dashboard built on Next.js.',
    descriptionHin: 'Documents manage karne ka system. Upload, preview, admin panel sab banaya gaya hai Next.js me.',
    tech: ['Next.js', 'PostgreSQL', 'S3', 'NextAuth'],
    accentColor: '#b026ff',
    accentColor2: '#ff003c',
    github: '#',
    live: '#',
    image: '',
    featured: false,
  },
]

// ─── Services data ────────────────────────────────────────────
export const SERVICES = [
  {
    icon: '🌐',
    title: 'Landing Pages',
    titleHin: 'Killer Landing Pages',
    description: 'High-converting, visually stunning landing pages that captivate visitors and drive action. Optimised for speed and SEO.',
    descriptionHin: 'Aise pages jo visitor ko fan bana dein. Full speed, full SEO. Product bikna tay hai.',
    features: ['Custom 3D animations', 'SEO & Performance optimized', 'Responsive design', 'CMS integration'],
    featuresHin: ['Custom 3D effects', 'SEO aur loading speed makkhan', 'Har screen pe fit', 'Easy update (CMS)'],
  },
  {
    icon: '🛒',
    title: 'E-Commerce Stores',
    titleHin: 'Online Dukaan',
    description: 'Full-featured online stores with payment gateways, inventory management, and seamless checkout experiences.',
    descriptionHin: 'Pura dukan online. Paise aayenge aur stock manage hoga bina kisi jhanjhat ke.',
    features: ['Stripe / Razorpay', 'Product management', 'Order tracking', 'Admin dashboard'],
    featuresHin: ['Razorpay/Stripe chalega', 'Product add karna aasan', 'Order track karo', 'Admin panel free'],
  },
  {
    icon: '⚡',
    title: 'Web Applications',
    titleHin: 'Bawaal Web Apps',
    description: 'Scalable, full-stack React & Next.js web apps with real-time features, APIs, and database integrations.',
    descriptionHin: 'Real-time, scalable apps jo aasaani se fatt-te nahi. Pura end-to-end full stack system.',
    features: ['REST & GraphQL APIs', 'Authentication', 'Real-time features', 'Cloud deployment'],
    featuresHin: ['Superfast APIs', 'Secure Login', 'Chat/Realtime features', 'Cloud par deploy'],
  },
  {
    icon: '🎮',
    title: '3D / Interactive Sites',
    titleHin: '3D Jadugari',
    description: 'Immersive Three.js + WebGL experiences with scroll-driven animations, 3D models, and interactive scenes.',
    descriptionHin: 'Browser me 3D game waali feeling. WebGL aur Three.js se bani sites jo ekdum premium feel deti hain.',
    features: ['Three.js / WebGL', 'GSAP scroll animations', 'Interactive 3D models', 'Shader effects'],
    featuresHin: ['Three.js / WebGL', 'GSAP magic animations', '3D models jo hilte hain', 'Cool shader effects'],
  },
]

// ─── Pricing plans ────────────────────────────────────────────
export const PRICING = [
  {
    name: 'Starter',
    nameHin: 'Basic Jugad',
    makingCost: '$199',
    hostingCost: '$5 – $10',
    hostingNote: '/month (Vercel + Domain)',
    hostingNoteHin: '/maheena (Domain ke paise)',
    description: 'Perfect for small businesses, freelancers, or personal brands needing a polished web presence.',
    descriptionHin: 'Chote business aur nayi personal branding ke liye ek number. Pura mast chalega.',
    features: [
      '3–5 page static website',
      'Responsive design',
      'Basic SEO setup',
      'Contact form',
      'Delivery in 5–7 days',
    ],
    featuresHin: [
      '3-5 page ki site',
      'Mobile par bhi 100/100',
      'Thoda SEO',
      'Form jisme mail aayega',
      'Hafte bhar me delivery',
    ],
    highlight: false,
  },
  {
    name: 'Pro',
    nameHin: 'Bawaal Pro',
    makingCost: '$499',
    hostingCost: '$15 – $30',
    hostingNote: '/month (VPS + SSL)',
    hostingNoteHin: '/maheena (High Speed VPS)',
    description: 'Full-stack web app or e-commerce store with CMS, payments, and admin panel.',
    descriptionHin: 'Full-stack app ya poori dukan. Payment lena aur database sambhalna apna kaam hai.',
    features: [
      'Full-stack Next.js app',
      'Payment integration',
      'Admin dashboard',
      'Database + API',
      '3D / interactive elements',
      'Delivery in 14–21 days',
    ],
    featuresHin: [
      'Proper Next.js ka app',
      'Payment gateweay chalu',
      'Admin ka apna dashboard',
      'Database aur API ready',
      'Thoda 3D tadka',
      '2 se 3 hafte me done',
    ],
    highlight: true,
  },
  {
    name: 'Enterprise',
    nameHin: 'Silaai Machine (Enterprise)',
    makingCost: 'Custom',
    hostingCost: 'Custom',
    hostingNote: 'on infrastructure requirements',
    hostingNoteHin: 'server ka bill kitna bhi ho sakta',
    description: 'Complex systems with microservices, cloud infrastructure, real-time features, and dedicated support.',
    descriptionHin: 'Sab kuch custom. Bada architecture jo traffic aane pe kabhi down na ho.',
    features: [
      'Microservices architecture',
      'Custom cloud setup (AWS/GCP)',
      'CI/CD pipeline',
      'Dedicated maintenance',
      'SLA-backed support',
      'Timeline: discussion based',
    ],
    featuresHin: [
      'Microservices (Badi planning)',
      'AWS ya GCP setup',
      'Auto-deploy pipeline',
      '24/7 dhyaan rakhna',
      'Contract base support',
      'Aaram se baith ke discuss karenge',
    ],
    highlight: false,
  },
]
